s = set()
#print(type(s))
#s_from_list = set([1,2,3])
#l = [4,5,6]
#s_from_list = set(l)
#print(s_from_list)
s.add(1)
s.add(1)
s.add(2)
#s1 = s.union({1,2,3})
#s1 = s.intersection({1,2,3})
#print(s, s1 )
s1= {1,2}
s.remove(2)
print(s.isdisjoint(s1))
print(len(s))